global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIASPDT5R6C5ULJ5HPF
        secret_key: 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
        port: 9100
