global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIASPDT5R6CWWALUEI6
        secret_key: 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
        port: 9100
