global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
      - files:
        - 'https://raw.githubusercontent.com/21chuks/prometheus-and-grafana-project/main/prometheus_serviceDiscovery.yml'
